agents:
  queue: "shaoting-gcp"

steps:
  - label: "Run full E2E Correctness Test"
    key: "full-e2e"
    commands:
      - bash .buildkite/correctness/e2e.sh
      - buildkite-agent artifact upload ".buildkite/correctness/results-*.png"