agents:
  queue: "shaoting-gcp"

steps:
  - label: "Setup"
    commands:
      - ./buildkite/correctness/env-setup.sh # this will generate a .buildkite/correctness/correctness_venv that every step should use

  - label: "Run E2E Correctness Test on a dense model"
    commands:
      - ./buildkite/correctness/e2e.sh meta-llama/Llama-3.1-8B

  - label: "Run E2E Correctness Test on an MLA model"
    commands:
      - ./buildkite/correctness/e2e.sh deepseek-ai/DeepSeek-V2-Lite

  - label: "Upload all pngs as artifacts"
    commands:
      - buildkite-agent artifact upload "results-*.png"
    depends_on:
      - "Run E2E Correctness Test on a dense model"
      - "Run E2E Correctness Test on an MLA model"